<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Nitins-MacBook-Pro.local" failures="2" tests="5" name="Test" time="64.573" errors="0" timestamp="2024-02-20T12:08:39 PST">
  <testcase classname="com.salesforce.automation.SalesforceCreateOpty_Testcases" name="OpportunityPipelineReport" time="9.156"/>
  <testcase classname="com.salesforce.automation.SalesforceCreateOpty_Testcases" name="QuarterlySummaryReport" time="8.692">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.salesforce.automation.SalesforceCreateOpty_Testcases.QuarterlySummaryReport(SalesforceCreateOpty_Testcases.java:192)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- QuarterlySummaryReport -->
  <testcase classname="com.salesforce.automation.SalesforceCreateOpty_Testcases" name="StuckOpportunitiesReport" time="8.552"/>
  <testcase classname="com.salesforce.automation.SalesforceCreateOpty_Testcases" name="createNewOppty" time="14.701">
    <failure type="java.lang.AssertionError" message="expected [https://dan000000cz3teag-dev-ed.develop.my.salesforce.com/006an000000lqXp] but found [https://dan000000cz3teag-dev-ed.develop.my.salesforce.com/006/e]">
      <![CDATA[java.lang.AssertionError: expected [https://dan000000cz3teag-dev-ed.develop.my.salesforce.com/006an000000lqXp] but found [https://dan000000cz3teag-dev-ed.develop.my.salesforce.com/006/e]
at com.salesforce.base.BaseClass.assertCurrentURL(BaseClass.java:273)
at com.salesforce.automation.SalesforceCreateOpty_Testcases.createNewOppty(SalesforceCreateOpty_Testcases.java:102)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- createNewOppty -->
  <testcase classname="com.salesforce.automation.SalesforceCreateOpty_Testcases" name="opportunitiesdropdown" time="7.521"/>
</testsuite> <!-- Test -->
